/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import cod.Dades;
import cod.init;
import static java.lang.Thread.sleep;
import java.lang.reflect.Field;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author T11380
 */
public class ventana extends javax.swing.JFrame {


    public ventana() throws InterruptedException {
        
        initComponents();
//        sleep(5000);
        replenaPantalla();
        
        System.out.println("asdfasdf");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscador = new javax.swing.JPanel();
        titolBuscador = new javax.swing.JLabel();
        inBuscador = new javax.swing.JTextField();
        panelTaulaPpal = new javax.swing.JPanel();
        panelTaules = new javax.swing.JPanel();
        titolTaula2 = new javax.swing.JLabel();
        titolTaula3 = new javax.swing.JLabel();
        titolTaula4 = new javax.swing.JLabel();
        titolTaula5 = new javax.swing.JLabel();
        titolTaula6 = new javax.swing.JLabel();
        titolTaula7 = new javax.swing.JLabel();
        titolTaula8 = new javax.swing.JLabel();
        titolTaula9 = new javax.swing.JLabel();
        titolTaula10 = new javax.swing.JLabel();
        titolTaula11 = new javax.swing.JLabel();
        titolTaula12 = new javax.swing.JLabel();
        titolTaula13 = new javax.swing.JLabel();
        titolTaula14 = new javax.swing.JLabel();
        titolTaula15 = new javax.swing.JLabel();
        titolTaula16 = new javax.swing.JLabel();
        scrollTaula2 = new javax.swing.JScrollPane();
        taula2 = new javax.swing.JTextArea();
        scrollTaula3 = new javax.swing.JScrollPane();
        taula3 = new javax.swing.JTextArea();
        scrollTaula4 = new javax.swing.JScrollPane();
        taula4 = new javax.swing.JTextArea();
        scrollTaula5 = new javax.swing.JScrollPane();
        taula5 = new javax.swing.JTextArea();
        scrollTaula6 = new javax.swing.JScrollPane();
        taula6 = new javax.swing.JTextArea();
        scrollTaula7 = new javax.swing.JScrollPane();
        taula7 = new javax.swing.JTextArea();
        scrollTaula8 = new javax.swing.JScrollPane();
        taula8 = new javax.swing.JTextArea();
        scrollTaula9 = new javax.swing.JScrollPane();
        taula9 = new javax.swing.JTextArea();
        scrollTaula10 = new javax.swing.JScrollPane();
        taula10 = new javax.swing.JTextArea();
        scrollTaula11 = new javax.swing.JScrollPane();
        taula11 = new javax.swing.JTextArea();
        scrollTaula12 = new javax.swing.JScrollPane();
        taula12 = new javax.swing.JTextArea();
        scrollTaula13 = new javax.swing.JScrollPane();
        taula13 = new javax.swing.JTextArea();
        scrollTaula14 = new javax.swing.JScrollPane();
        taula14 = new javax.swing.JTextArea();
        scrollTaula15 = new javax.swing.JScrollPane();
        taula15 = new javax.swing.JTextArea();
        scrollTaula16 = new javax.swing.JScrollPane();
        taula16 = new javax.swing.JTextArea();
        panelMapa = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        titolTaula1 = new javax.swing.JLabel();
        scrollTaula1 = new javax.swing.JScrollPane();
        taula1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titolBuscador.setText("Introduiu el vostre nom");

        inBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBuscadorActionPerformed(evt);
            }
        });
        inBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inBuscadorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscadorLayout = new javax.swing.GroupLayout(panelBuscador);
        panelBuscador.setLayout(panelBuscadorLayout);
        panelBuscadorLayout.setHorizontalGroup(
            panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titolBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelBuscadorLayout.setVerticalGroup(
            panelBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titolBuscador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTaulaPpalLayout = new javax.swing.GroupLayout(panelTaulaPpal);
        panelTaulaPpal.setLayout(panelTaulaPpalLayout);
        panelTaulaPpalLayout.setHorizontalGroup(
            panelTaulaPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        panelTaulaPpalLayout.setVerticalGroup(
            panelTaulaPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        titolTaula2.setText("Taula 2");

        titolTaula3.setText("Taula 3");

        titolTaula4.setText("Taula 4");

        titolTaula5.setText("Taula 5");

        titolTaula6.setText("Taula 6");

        titolTaula7.setText("Taula 7");

        titolTaula8.setText("Taula 8");

        titolTaula9.setText("Taula 9");

        titolTaula10.setText("Taula 10");

        titolTaula11.setText("Taula 11");

        titolTaula12.setText("Taula 12");

        titolTaula13.setText("Taula 13");

        titolTaula14.setText("Taula 14");

        titolTaula15.setText("Taula 15");

        titolTaula16.setText("Taula 16");

        taula2.setColumns(10);
        taula2.setRows(5);
        taula2.setAutoscrolls(false);
        taula2.setEnabled(false);
        taula2.setFocusable(false);
        taula2.setRequestFocusEnabled(false);
        taula2.setVerifyInputWhenFocusTarget(false);
        scrollTaula2.setViewportView(taula2);

        taula3.setColumns(10);
        taula3.setRows(5);
        taula3.setAutoscrolls(false);
        taula3.setEnabled(false);
        taula3.setFocusable(false);
        taula3.setRequestFocusEnabled(false);
        taula3.setVerifyInputWhenFocusTarget(false);
        scrollTaula3.setViewportView(taula3);

        taula4.setColumns(10);
        taula4.setRows(5);
        taula4.setAutoscrolls(false);
        taula4.setEnabled(false);
        taula4.setFocusable(false);
        taula4.setRequestFocusEnabled(false);
        taula4.setVerifyInputWhenFocusTarget(false);
        scrollTaula4.setViewportView(taula4);

        taula5.setColumns(10);
        taula5.setRows(5);
        taula5.setAutoscrolls(false);
        taula5.setEnabled(false);
        taula5.setFocusable(false);
        taula5.setRequestFocusEnabled(false);
        taula5.setVerifyInputWhenFocusTarget(false);
        scrollTaula5.setViewportView(taula5);

        taula6.setColumns(10);
        taula6.setRows(5);
        taula6.setAutoscrolls(false);
        taula6.setEnabled(false);
        taula6.setFocusable(false);
        taula6.setRequestFocusEnabled(false);
        taula6.setVerifyInputWhenFocusTarget(false);
        scrollTaula6.setViewportView(taula6);

        taula7.setColumns(10);
        taula7.setRows(5);
        taula7.setAutoscrolls(false);
        taula7.setEnabled(false);
        taula7.setFocusable(false);
        taula7.setRequestFocusEnabled(false);
        taula7.setVerifyInputWhenFocusTarget(false);
        scrollTaula7.setViewportView(taula7);

        taula8.setColumns(10);
        taula8.setRows(5);
        taula8.setAutoscrolls(false);
        taula8.setEnabled(false);
        taula8.setFocusable(false);
        taula8.setRequestFocusEnabled(false);
        taula8.setVerifyInputWhenFocusTarget(false);
        scrollTaula8.setViewportView(taula8);

        taula9.setColumns(10);
        taula9.setRows(5);
        taula9.setAutoscrolls(false);
        taula9.setEnabled(false);
        taula9.setFocusable(false);
        taula9.setRequestFocusEnabled(false);
        taula9.setVerifyInputWhenFocusTarget(false);
        scrollTaula9.setViewportView(taula9);

        taula10.setColumns(10);
        taula10.setRows(5);
        taula10.setAutoscrolls(false);
        taula10.setEnabled(false);
        taula10.setFocusable(false);
        taula10.setRequestFocusEnabled(false);
        taula10.setVerifyInputWhenFocusTarget(false);
        scrollTaula10.setViewportView(taula10);

        taula11.setColumns(10);
        taula11.setRows(5);
        taula11.setAutoscrolls(false);
        taula11.setEnabled(false);
        taula11.setFocusable(false);
        taula11.setRequestFocusEnabled(false);
        taula11.setVerifyInputWhenFocusTarget(false);
        scrollTaula11.setViewportView(taula11);

        taula12.setColumns(10);
        taula12.setRows(5);
        taula12.setAutoscrolls(false);
        taula12.setEnabled(false);
        taula12.setFocusable(false);
        taula12.setRequestFocusEnabled(false);
        taula12.setVerifyInputWhenFocusTarget(false);
        scrollTaula12.setViewportView(taula12);

        taula13.setColumns(10);
        taula13.setRows(5);
        taula13.setAutoscrolls(false);
        taula13.setEnabled(false);
        taula13.setFocusable(false);
        taula13.setRequestFocusEnabled(false);
        taula13.setVerifyInputWhenFocusTarget(false);
        scrollTaula13.setViewportView(taula13);

        taula14.setColumns(10);
        taula14.setRows(5);
        taula14.setAutoscrolls(false);
        taula14.setEnabled(false);
        taula14.setFocusable(false);
        taula14.setRequestFocusEnabled(false);
        taula14.setVerifyInputWhenFocusTarget(false);
        scrollTaula14.setViewportView(taula14);

        taula15.setColumns(10);
        taula15.setRows(5);
        taula15.setAutoscrolls(false);
        taula15.setEnabled(false);
        taula15.setFocusable(false);
        taula15.setRequestFocusEnabled(false);
        taula15.setVerifyInputWhenFocusTarget(false);
        scrollTaula15.setViewportView(taula15);

        taula16.setColumns(10);
        taula16.setRows(5);
        taula16.setAutoscrolls(false);
        taula16.setEnabled(false);
        taula16.setFocusable(false);
        taula16.setRequestFocusEnabled(false);
        taula16.setVerifyInputWhenFocusTarget(false);
        scrollTaula16.setViewportView(taula16);

        javax.swing.GroupLayout panelTaulesLayout = new javax.swing.GroupLayout(panelTaules);
        panelTaules.setLayout(panelTaulesLayout);
        panelTaulesLayout.setHorizontalGroup(
            panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaulesLayout.createSequentialGroup()
                .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTaulesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titolTaula12)
                            .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelTaulesLayout.createSequentialGroup()
                                    .addComponent(titolTaula2)
                                    .addGap(111, 111, 111)
                                    .addComponent(titolTaula3)
                                    .addGap(117, 117, 117)
                                    .addComponent(titolTaula4)
                                    .addGap(118, 118, 118)
                                    .addComponent(titolTaula5)
                                    .addGap(106, 106, 106)
                                    .addComponent(titolTaula6)
                                    .addGap(6, 6, 6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTaulesLayout.createSequentialGroup()
                                    .addComponent(titolTaula7)
                                    .addGap(111, 111, 111)
                                    .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titolTaula8)
                                        .addComponent(titolTaula13))
                                    .addGap(111, 111, 111)
                                    .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titolTaula9)
                                        .addComponent(titolTaula14))
                                    .addGap(112, 112, 112)
                                    .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelTaulesLayout.createSequentialGroup()
                                            .addComponent(titolTaula10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(titolTaula11)
                                            .addGap(7, 7, 7))
                                        .addGroup(panelTaulesLayout.createSequentialGroup()
                                            .addComponent(titolTaula15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(titolTaula16)
                                            .addGap(8, 8, 8)))))))
                    .addGroup(panelTaulesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollTaula2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(scrollTaula3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(scrollTaula4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(scrollTaula5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(scrollTaula6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTaulesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollTaula11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(scrollTaula10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(scrollTaula9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(scrollTaula8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(scrollTaula7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTaulesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollTaula16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(scrollTaula15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(scrollTaula14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(scrollTaula13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(scrollTaula12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTaulesLayout.setVerticalGroup(
            panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaulesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titolTaula2)
                    .addComponent(titolTaula3)
                    .addComponent(titolTaula4)
                    .addComponent(titolTaula5)
                    .addComponent(titolTaula6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTaula2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTaulesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titolTaula7)
                            .addComponent(titolTaula8)
                            .addComponent(titolTaula9)
                            .addComponent(titolTaula10)))
                    .addGroup(panelTaulesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titolTaula11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTaula11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titolTaula12)
                    .addComponent(titolTaula13)
                    .addComponent(titolTaula14)
                    .addComponent(titolTaula15)
                    .addComponent(titolTaula16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTaulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTaula16, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula14, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula15, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTaula12, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        titolTaula1.setText("Taula 1");

        taula1.setColumns(10);
        taula1.setRows(5);
        taula1.setAutoscrolls(false);
        taula1.setFocusable(false);
        taula1.setRequestFocusEnabled(false);
        taula1.setVerifyInputWhenFocusTarget(false);
        scrollTaula1.setViewportView(taula1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelTaulaPpal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(titolTaula1)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollTaula1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelTaules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTaulaPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titolTaula1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrollTaula1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTaules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inBuscadorActionPerformed

    private void inBuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inBuscadorKeyPressed
        
        int tecla = evt.getKeyCode();
        replenaPantalla();
        if (tecla==evt.VK_A || tecla==evt.VK_B || tecla==evt.VK_C || tecla==evt.VK_D || tecla==evt.VK_E || tecla==evt.VK_F || tecla==evt.VK_G || 
        tecla==evt.VK_H || tecla==evt.VK_I || tecla==evt.VK_J || tecla==evt.VK_K || tecla==evt.VK_L || tecla==evt.VK_M || tecla==evt.VK_N || 
        tecla==evt.VK_O || tecla==evt.VK_P || tecla==evt.VK_Q || tecla==evt.VK_R || tecla==evt.VK_S || tecla==evt.VK_T || tecla==evt.VK_U || 
        tecla==evt.VK_V || tecla==evt.VK_W || tecla==evt.VK_X || tecla==evt.VK_Y || tecla==evt.VK_Z || tecla==evt.VK_SPACE || 
        "Ñ".equalsIgnoreCase(Character.toString(evt.getKeyChar())) || "Ç".equalsIgnoreCase(Character.toString(evt.getKeyChar()))) {
            
            
            
        } else if (tecla==evt.VK_F1 || tecla==evt.VK_ESCAPE) {
            
        } else if (tecla==evt.VK_BACK_SPACE) {
            
        } else if (tecla==evt.VK_F12) {
            System.exit(0);
        } else {
            System.out.println("tecla pulsada: '"+evt.getKeyChar()+"' codi: "+tecla);
        }
            
    }//GEN-LAST:event_inBuscadorKeyPressed

    private void replenaPantalla() {
        
        Dades dades = init.dades;
        Class clase = ventana.class;
        
//        reflexioPerReplenar();
        try {
            for (int i=1; i<=dades.getNumTaules(); i++) {
                if (dades.getTaula().get(i).getNumTaula()>0) {
                    JTextArea aux = new JTextArea();
                    String meth = "taula"+dades.getTaula().get(i).getNumTaula();
//                    System.out.println("meth: "+meth);
                    if (dades.getTaula().get(i).getCapacitatTaula()>0) {
                        Field var = clase.getDeclaredField(meth);
//                        System.out.println("var: "+var.getName());
                        String lite = "";
                        for (int j=0; j<dades.getTaula().get(i).getConvidat().size(); j++) {
                            lite += dades.getTaula().get(i).getConvidat().get(j).getNom()+"\n";
                        }
                        aux.setText(lite);
                        aux.setEnabled(true);
                        var.set(this, aux);
                    }
                }
                
            }
//            System.exit(0);
        } catch (Exception e) {
            System.out.println("EstasPetando¿?"+e.toString());
            System.exit(0);
        }
        
        System.out.println("Taula1: "+taula1.getText());
        
    }
    
    private void reflexioPerReplenar() {
        
        Class clase = ventana.class;
        
        Field [] variables = clase.getDeclaredFields();
        for (int i=0; i<variables.length; i++) {
            System.out.println("var. "+variables[i].getName());
        }
        try {
            
            JTextArea aux = (JTextArea) variables[0].get(this);
        } catch (Exception e) {
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ventana().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inBuscador;
    private javax.swing.JPanel panelBuscador;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JPanel panelTaulaPpal;
    private javax.swing.JPanel panelTaules;
    private javax.swing.JScrollPane scrollTaula1;
    private javax.swing.JScrollPane scrollTaula10;
    private javax.swing.JScrollPane scrollTaula11;
    private javax.swing.JScrollPane scrollTaula12;
    private javax.swing.JScrollPane scrollTaula13;
    private javax.swing.JScrollPane scrollTaula14;
    private javax.swing.JScrollPane scrollTaula15;
    private javax.swing.JScrollPane scrollTaula16;
    private javax.swing.JScrollPane scrollTaula2;
    private javax.swing.JScrollPane scrollTaula3;
    private javax.swing.JScrollPane scrollTaula4;
    private javax.swing.JScrollPane scrollTaula5;
    private javax.swing.JScrollPane scrollTaula6;
    private javax.swing.JScrollPane scrollTaula7;
    private javax.swing.JScrollPane scrollTaula8;
    private javax.swing.JScrollPane scrollTaula9;
    private javax.swing.JTextArea taula1;
    private javax.swing.JTextArea taula10;
    private javax.swing.JTextArea taula11;
    private javax.swing.JTextArea taula12;
    private javax.swing.JTextArea taula13;
    private javax.swing.JTextArea taula14;
    private javax.swing.JTextArea taula15;
    private javax.swing.JTextArea taula16;
    private javax.swing.JTextArea taula2;
    private javax.swing.JTextArea taula3;
    private javax.swing.JTextArea taula4;
    private javax.swing.JTextArea taula5;
    private javax.swing.JTextArea taula6;
    private javax.swing.JTextArea taula7;
    private javax.swing.JTextArea taula8;
    private javax.swing.JTextArea taula9;
    private javax.swing.JLabel titolBuscador;
    private javax.swing.JLabel titolTaula1;
    private javax.swing.JLabel titolTaula10;
    private javax.swing.JLabel titolTaula11;
    private javax.swing.JLabel titolTaula12;
    private javax.swing.JLabel titolTaula13;
    private javax.swing.JLabel titolTaula14;
    private javax.swing.JLabel titolTaula15;
    private javax.swing.JLabel titolTaula16;
    private javax.swing.JLabel titolTaula2;
    private javax.swing.JLabel titolTaula3;
    private javax.swing.JLabel titolTaula4;
    private javax.swing.JLabel titolTaula5;
    private javax.swing.JLabel titolTaula6;
    private javax.swing.JLabel titolTaula7;
    private javax.swing.JLabel titolTaula8;
    private javax.swing.JLabel titolTaula9;
    // End of variables declaration//GEN-END:variables
}
